language: cpp
compiler: g++
dist: trusty
sudo: required

addons:
    apt:
        sources:
            - george-edison55-precise-backports
            - boost-latest
        packages:
            - build-essential
            - cmake
            - cmake-data
            - libicu-dev
            - libboost-all-dev
            - zlib1g-dev
            - libssl-dev
install:
    - mkdir deps && cd deps
    - wget http://www.nih.at/libzip/libzip-1.1.2.tar.gz && tar -zxvf libzip-1.1.2.tar.gz && cd libzip-1.1.2 && cmake . && make && sudo make install && sudo cp zipconf.h /usr/local/include && cd ..
    - wget http://www.rarlab.com/rar/unrarsrc-5.3.11.tar.gz && tar -zxvf unrarsrc-5.3.11.tar.gz && cd unrar && make lib && sudo make install-lib && sudo mkdir /usr/local/include/unrar && sudo cp dll.hpp /usr/local/include/unrar && cd ..
    - git clone https://github.com/no1msd/mstch && cd mstch && mkdir build && cd build && cmake .. && make && sudo make install && cd ../..
    - git clone https://github.com/itseez/opencv && cd opencv && mkdir build && cd build
    - cmake -D WITH_IPP=OFF -D WITH_IPP_A=OFF -D WITH_JASPER=OFF -D WITH_OPENEXR=OFF -D WITH_TBB=OFF -D WITH_TIFF=OFF -D WITH_WEBP=OFF -D BUILD_opencv_calib3d=OFF -D BUILD_opencv_flann=OFF -D BUILD_opencv_ml=OFF -D BUILD_opencv_photo=OFF -D BUILD_opencv_video=OFF -D BUILD_opencv_shape=OFF -D BUILD_opencv_objdetect=OFF -D BUILD_opencv_superres=OFF -D BUILD_opencv_ts=OFF ..
    - make && sudo make install && cd ../../..
    - mkdir build && cd build
script:
    - cmake ..
    - make
cache:
    apt
